### ISSUE TITLE
Can't build on Mac

### ISSUE THREAD

**Issue by etinin** [Josko/aura-bot#40]
I can build the bot perfectly on Linux.

On the Mac, however I get the following error when using make:

src/crc32.cpp:73:43: error: no matching function for call to 'swap'
      const uint32_t one   = *current++ ^ swap(crc);

Not completely sure why it only fails on the Mac, but I guess it's due to swap function availability by the compiler.
Could apparently fix it by implementing the swap function:

```
/* Swap the bytes in a word_t.  This can be replaced by a byte-swap builtin, if
   available on the compiler.  E.g. __builtin_bswap64() on gcc and clang.  The
   speed of swap() is inconsequential however, being used at most twice per
   crc_wordwise() call.  It is only used on little-endian machines if the CRC
   is not reflected, or on big-endian machines if the CRC is reflected. */
static inline word_t swap(word_t x)
{
    word_t y;
    unsigned n = WORDCHARS - 1;

    y = x & 0xff;
    while (x >>= 8) {
        y <<= 8;
        y |= x & 0xff;
        n--;
    }
    return y << (n << 3);
}

```

**Comment by Argon-** [comment]
Are you sure you are using the current master? Your line numbers do not match mine. Also, are you using clang? Because I got an differently phrased error message.

The problem is not the swap function but that this part of the code is even looked at. OSX on Intel is little endian. No idea why `__BIG_ENDIAN` (which shouldn't be set) was somehow defined(?).

**Comment by Josko** [comment]
swap() function body was added in commit c832e6838ded0c88185f5ce8861cda216e81e539 (master branch), please try that commit.
